In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pickle
import pandas as pd
%matplotlib inline
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings('ignore')
import math
plt.rcParams.update({'font.size': 13})
from collections import defaultdict

In [2]:
datasets = ['mnist10', 'mnist30', 'mnist100', 'mnist1000', 'mnist3000', 'mnist10000']

In [3]:
ls ../pSTN-baselines/experiments/grid_search_mnist_affine/

'pstn_mnist1000_0.01_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.01_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.01_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.01_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.05_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.05_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.05_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.05_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.15_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.15_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.15_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.15_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.01_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.1_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.01_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.1_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.01_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.1_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.01_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.1_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.25_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.25_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.25_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.25_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.2_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.2_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.2_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.2_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.35_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.35_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.35_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.35_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.3_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.3_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.3_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.3_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.4_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.4_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist1000_0.4_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist1000_0.4_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.05_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.05_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.05_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.05_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.15_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.15_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.15_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.15_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.01_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.1_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.01_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.1_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.01_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.1_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.01_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.1_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.25_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.25_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.25_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.25_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.2_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.2_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.2_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.2_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.35_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.35_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.35_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.35_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.3_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.3_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.3_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.3_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist100_0.4_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.4_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist100_0.4_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist100_0.4_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.05_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.05_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.05_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.05_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.15_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.15_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.15_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.15_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.1_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.1_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.1_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.1_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.25_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.25_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.25_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.25_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.2_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.2_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.2_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.2_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.35_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.35_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.35_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.35_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.3_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.3_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.3_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.3_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist10_0.4_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.4_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist10_0.4_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist10_0.4_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.25_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.25_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.25_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.25_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.35_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.35_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.35_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.35_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.3_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.3_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.3_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.3_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist3000_0.4_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist3000_0.4_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.01_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.01_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.01_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.01_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.05_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.05_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.05_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.05_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.15_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.15_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.15_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.15_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.1_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.1_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.1_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.1_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.25_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.25_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.25_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.25_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.2_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.2_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.2_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.2_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.35_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.35_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.35_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.35_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.3_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.3_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.3_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.3_fold_1_DA=None_affine_test_loss.p'
'pstn_mnist30_0.4_fold_0_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.4_fold_0_DA=None_affine_test_loss.p'
'pstn_mnist30_0.4_fold_1_DA=None_affine_test_accuracy.p'
'pstn_mnist30_0.4_fold_1_DA=None_affine_test_loss.p'

__P_STN__

In [4]:
priors = [0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]

In [5]:
#### P_STN
def create_results_df(dataset):
    # LOAD RESULTS
    P_STN_test_losses = defaultdict(list)
    P_STN_accuracy = defaultdict(list)
    for prior in priors:
        for fold in range(2):
            try:
                P_STN_test_losses[prior].append(pickle.load(open('../pSTN-baselines/experiments/grid_search_mnist_affine/pstn_%s_%s_fold_%s_DA=None_affine_test_loss.p' %(dataset, prior, fold), 'rb')))
                P_STN_accuracy[prior].append(pickle.load(open('../pSTN-baselines/experiments/grid_search_mnist_affine/pstn_%s_%s_fold_%s_DA=None_affine_test_accuracy.p' %(dataset, prior, fold), 'rb')))
            except:
                print('not done yet with', dataset, fold)
    P_STN_accs = {prior: [np.mean(P_STN_accuracy[prior]), np.std(P_STN_accuracy[prior])] for prior in priors}
    P_STN_accs_df = pd.DataFrame.from_dict(P_STN_accs, orient='index', columns = ['mean', 'std'])
    print('%s results are'%dataset)
    return P_STN_accs_df

In [6]:
create_results_df('mnist10')

mnist10 results are

         mean      std
0.01  0.48980  0.12860
0.05  0.55085  0.09995
0.10  0.55865  0.09775
0.15  0.50530  0.05900
0.20  0.47025  0.06925
0.25  0.46395  0.05605
0.30  0.42060  0.08160
0.35  0.29375  0.03735
0.40  0.27310  0.03020

In [7]:
create_results_df('mnist30')

mnist30 results are

         mean      std
0.01  0.69745  0.00545
0.05  0.75150  0.00310
0.10  0.77855  0.01465
0.15  0.79160  0.00380
0.20  0.79510  0.01040
0.25  0.75350  0.01910
0.30  0.69375  0.06045
0.35  0.66395  0.02675
0.40  0.58675  0.07725

In [8]:
create_results_df('mnist100')

mnist100 results are

         mean      std
0.01  0.87300  0.01400
0.05  0.91235  0.00835
0.10  0.93410  0.00560
0.15  0.93365  0.00625
0.20  0.92505  0.00175
0.25  0.92510  0.00220
0.30  0.91065  0.00225
0.35  0.89350  0.01390
0.40  0.84775  0.01555

In [9]:
create_results_df('mnist1000')

mnist1000 results are

         mean      std
0.01  0.95735  0.00275
0.05  0.96715  0.00135
0.10  0.97275  0.00305
0.15  0.97305  0.00425
0.20  0.97060  0.00020
0.25  0.95500  0.00720
0.30  0.95475  0.00015
0.35  0.94510  0.01120
0.40  0.93760  0.00070

In [10]:
create_results_df('mnist3000')

not done yet with mnist3000 0
not done yet with mnist3000 1
not done yet with mnist3000 0
not done yet with mnist3000 1
not done yet with mnist3000 0
not done yet with mnist3000 1
not done yet with mnist3000 0
not done yet with mnist3000 1
not done yet with mnist3000 0
not done yet with mnist3000 1
not done yet with mnist3000 1
mnist3000 results are

        mean     std
0.01     NaN     NaN
0.05     NaN     NaN
0.10     NaN     NaN
0.15     NaN     NaN
0.20     NaN     NaN
0.25  0.9640  0.0005
0.30  0.9632  0.0004
0.35  0.9549  0.0058
0.40  0.9404  0.0000

In [11]:
create_results_df('mnist10000')

not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
not done yet with mnist10000 0
not done yet with mnist10000 1
mnist10000 results are

      mean  std
0.01   NaN  NaN
0.05   NaN  NaN
0.10   NaN  NaN
0.15   NaN  NaN
0.20   NaN  NaN
0.25   NaN  NaN
0.30   NaN  NaN
0.35   NaN  NaN
0.40   NaN  NaN